jaffle_shop:
  outputs:
    dev:
      dremio_space: '@user'
      dremio_space_folder: no_schema
      object_storage_path: dbtdremios3
      object_storage_source: dbt_test_source
      password: dremio123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: dremio
  target: dev
