version: 2

models:
  - name: stg_customers
    description: Customer data with basic cleaning and transformation applied, one row per customer.
    columns:
      - name: customer_id
        description: The unique key for each customer.
        tests:
          - not_null
          - unique
        data_type: text
      - name: customer_name
        data_type: text

  - name: stg_locations
    description: List of open locations with basic cleaning and transformation applied, one row per location.
    columns:
      - name: location_id
        description: The unique key for each location.
        tests:
          - not_null
          - unique
        data_type: text
      - name: location_name
        data_type: text
      - name: tax_rate
        data_type: float
      - name: opened_at
        data_type: timestamp_ntz

  - name: stg_order_items
    description: Individual food and drink items that make up our orders, one row per item.
    columns:
      - name: order_item_id
        description: The unique key for each order item.
        tests:
          - not_null
          - unique
        data_type: text
      - name: order_id
        data_type: text
      - name: product_id
        data_type: text

  - name: stg_orders
    description: Order data with basic cleaning and transformation applied, one row per order.
    columns:
      - name: order_id
        description: The unique key for each order.
        tests:
          - not_null
          - unique
        data_type: text
      - name: location_id
        data_type: text
      - name: customer_id
        data_type: text
      - name: order_total
        data_type: number
      - name: tax_paid
        data_type: number
      - name: ordered_at
        data_type: timestamp_ntz

  - name: stg_products
    description: Product (food and drink items that can be ordered) data with basic cleaning and transformation applied, one row per product.
    columns:
      - name: product_id
        description: The unique key for each product.
        tests:
          - not_null
          - unique
        data_type: text
      - name: product_name
        data_type: text
      - name: product_type
        data_type: text
      - name: product_description
        data_type: text
      - name: product_price
        data_type: number
      - name: is_food_item
        data_type: boolean
      - name: is_drink_item
        data_type: boolean
        
  - name: stg_supplies
    description: >
      List of our supply expenses data with basic cleaning and transformation applied.

      One row per supply cost, not per supply. As supply costs fluctuate they receive a new row with a new UUID. Thus there can be multiple rows per supply_id.
    columns:
      - name: supply_uuid
        description: The unique key of our supplies per cost.
        tests:
          - not_null
          - unique
        data_type: text
      - name: supply_id
        data_type: text
      - name: product_id
        data_type: text
      - name: supply_name
        data_type: text
      - name: supply_cost
        data_type: number
      - name: is_perishable_supply
        data_type: boolean